services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_CONN=todo.db
      - MONGO_URI=mongodb://mongo:27017/todo
      - HOST=http://localhost:8080
  mongo:
    image: mongo:6


