services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_CONN=todo.db
      - MONGO_URI=mongodb://mongo:27017/todo
      - HOST=http://localhost:8080
      - GIN_MODE=release
  mongo:
    image: mongo:6
  alot:
    build:
      context: ./cmd/alot/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - API_URL=http://my-app:8080/transfer/"
      - GIN_MODE=release


